version: "3.0"
services:
  ponyoponyo-webapp:
    build:
      context: ./app/
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
